"""
Pricing data for OpenAI models.

This module contains the pricing data for OpenAI models in dictionary format.
Auto-generated by openai_pricing_scraper.py
Last updated: 2025-11-25 00:59:02
"""

# Pricing data in dollars per 1M tokens (input/cached_input/output)
PRICING_DATA = {
    # Format: (model_name, version): {"input_price": float, "cached_input_price": float, "output_price": float}
    ("gpt-5.1", "latest"): {
        "input_price": 1.2500,
        "cached_input_price": 0.1250,
        "output_price": 10.0000,
    },
    ("gpt-5", "latest"): {
        "input_price": 1.2500,
        "cached_input_price": 0.1250,
        "output_price": 10.0000,
    },
    ("gpt-5-mini", "latest"): {
        "input_price": 0.2500,
        "cached_input_price": 0.0250,
        "output_price": 2.0000,
    },
    ("gpt-5-nano", "latest"): {
        "input_price": 0.0500,
        "cached_input_price": 0.0050,
        "output_price": 0.4000,
    },
    ("gpt-5.1-chat-latest", "latest"): {
        "input_price": 1.2500,
        "cached_input_price": 0.1250,
        "output_price": 10.0000,
    },
    ("gpt-5-chat-latest", "latest"): {
        "input_price": 1.2500,
        "cached_input_price": 0.1250,
        "output_price": 10.0000,
    },
    ("gpt-5.1-codex", "latest"): {
        "input_price": 1.2500,
        "cached_input_price": 0.1250,
        "output_price": 10.0000,
    },
    ("gpt-5-codex", "latest"): {
        "input_price": 1.2500,
        "cached_input_price": 0.1250,
        "output_price": 10.0000,
    },
    ("gpt-5-pro", "latest"): {
        "input_price": 15.0000,
        "cached_input_price": 0.0000,
        "output_price": 120.0000,
    },
    ("gpt-4.1", "latest"): {
        "input_price": 2.0000,
        "cached_input_price": 0.5000,
        "output_price": 8.0000,
    },
    ("gpt-4.1-mini", "latest"): {
        "input_price": 0.4000,
        "cached_input_price": 0.1000,
        "output_price": 1.6000,
    },
    ("gpt-4.1-nano", "latest"): {
        "input_price": 0.1000,
        "cached_input_price": 0.0250,
        "output_price": 0.4000,
    },
    ("gpt-4o", "latest"): {
        "input_price": 2.5000,
        "cached_input_price": 1.2500,
        "output_price": 10.0000,
    },
    ("gpt-4o-2024-05-13", "latest"): {
        "input_price": 5.0000,
        "cached_input_price": 0.0000,
        "output_price": 15.0000,
    },
    ("gpt-4o-mini", "latest"): {
        "input_price": 0.1500,
        "cached_input_price": 0.0750,
        "output_price": 0.6000,
    },
    ("gpt-realtime", "latest"): {
        "input_price": 4.0000,
        "cached_input_price": 0.4000,
        "output_price": 16.0000,
    },
    ("gpt-realtime-mini", "latest"): {
        "input_price": 0.6000,
        "cached_input_price": 0.0600,
        "output_price": 2.4000,
    },
    ("gpt-4o-realtime-preview", "latest"): {
        "input_price": 5.0000,
        "cached_input_price": 2.5000,
        "output_price": 20.0000,
    },
    ("gpt-4o-mini-realtime-preview", "latest"): {
        "input_price": 0.6000,
        "cached_input_price": 0.3000,
        "output_price": 2.4000,
    },
    ("gpt-audio", "latest"): {
        "input_price": 2.5000,
        "cached_input_price": 0.0000,
        "output_price": 10.0000,
    },
    ("gpt-audio-mini", "latest"): {
        "input_price": 0.6000,
        "cached_input_price": 0.0000,
        "output_price": 2.4000,
    },
    ("gpt-4o-audio-preview", "latest"): {
        "input_price": 2.5000,
        "cached_input_price": 0.0000,
        "output_price": 10.0000,
    },
    ("gpt-4o-mini-audio-preview", "latest"): {
        "input_price": 0.1500,
        "cached_input_price": 0.0000,
        "output_price": 0.6000,
    },
    ("o1", "latest"): {
        "input_price": 15.0000,
        "cached_input_price": 7.5000,
        "output_price": 60.0000,
    },
    ("o1-pro", "latest"): {
        "input_price": 150.0000,
        "cached_input_price": 0.0000,
        "output_price": 600.0000,
    },
    ("o3-pro", "latest"): {
        "input_price": 20.0000,
        "cached_input_price": 0.0000,
        "output_price": 80.0000,
    },
    ("o3", "latest"): {
        "input_price": 2.0000,
        "cached_input_price": 0.5000,
        "output_price": 8.0000,
    },
    ("o3-deep-research", "latest"): {
        "input_price": 10.0000,
        "cached_input_price": 2.5000,
        "output_price": 40.0000,
    },
    ("o4-mini", "latest"): {
        "input_price": 1.1000,
        "cached_input_price": 0.2750,
        "output_price": 4.4000,
    },
    ("o4-mini-deep-research", "latest"): {
        "input_price": 2.0000,
        "cached_input_price": 0.5000,
        "output_price": 8.0000,
    },
    ("o3-mini", "latest"): {
        "input_price": 1.1000,
        "cached_input_price": 0.5500,
        "output_price": 4.4000,
    },
    ("o1-mini", "latest"): {
        "input_price": 1.1000,
        "cached_input_price": 0.5500,
        "output_price": 4.4000,
    },
    ("gpt-5.1-codex-mini", "latest"): {
        "input_price": 0.2500,
        "cached_input_price": 0.0250,
        "output_price": 2.0000,
    },
    ("codex-mini-latest", "latest"): {
        "input_price": 1.5000,
        "cached_input_price": 0.3750,
        "output_price": 6.0000,
    },
    ("gpt-5-search-api", "latest"): {
        "input_price": 1.2500,
        "cached_input_price": 0.1250,
        "output_price": 10.0000,
    },
    ("gpt-4o-mini-search-preview", "latest"): {
        "input_price": 0.1500,
        "cached_input_price": 0.0000,
        "output_price": 0.6000,
    },
    ("gpt-4o-search-preview", "latest"): {
        "input_price": 2.5000,
        "cached_input_price": 0.0000,
        "output_price": 10.0000,
    },
    ("computer-use-preview", "latest"): {
        "input_price": 3.0000,
        "cached_input_price": 0.0000,
        "output_price": 12.0000,
    },
    ("gpt-image-1", "latest"): {
        "input_price": 5.0000,
        "cached_input_price": 1.2500,
        "output_price": 0.0000,
    },
    ("gpt-image-1-mini", "latest"): {
        "input_price": 2.0000,
        "cached_input_price": 0.2000,
        "output_price": 0.0000,
    },
}
